# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ac2eebb17307f44da3a816b4089004fbe32d713097ca8c81df70db3c6a3dd280fc475b707d4dc44b413b02aeff4fce1b6ddd8239a3c02fc79c05af27dcffd6f

test:
  secret_key_base: 23244c3a12c9f0c32fe73d597b917b2adbf7f8f9047df7f9c618dc40d41f96cb629066894ce8876ad37fffd8a0beda3f102dc06c0c47ed139be5c6e8a3ab6652

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
